# Generated by Django 2.2 on 2019-08-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'INTERNAL'), (1, 'EXTERNAL'), (2, 'IMG'), (3, 'GIF'), (4, 'VID')], default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('popularity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('comments_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.CharField(default='', max_length=255)),
                ('sticky', models.BooleanField(default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='communities.Community')),
            ],
            options={
                'ordering': ('-creation_date', '-votes'),
            },
        ),
    ]
