# Generated by Django 2.2 on 2019-08-06 15:18

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invitation_required', models.BooleanField(default=False)),
                ('adult', models.BooleanField(default=False)),
                ('text_color', models.PositiveSmallIntegerField(default=0)),
                ('background_color', models.PositiveSmallIntegerField(default=0)),
                ('background_img', models.ImageField(blank=True, null=True, upload_to=communities.models.img_filename_generator, validators=[communities.models.file_size_validator])),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
